### ISSUE TITLE
hostname verification against certificate is already done by IO::Socket::SSL - no need to reimplement it (and implement it wrong)

### ISSUE THREAD

**Issue by noxxi** [libwww-perl/LWP-Protocol-https#13]
Hi,
checking if a certificate matches the hostname is already done by IO::Socket::SSL and LWP::Protocol::https sets also the necessary SSL_verifycn_scheme to www. So there is no need to reimplement it like done with _cn_match and _in_san. 

Apart from that the code is wrong, e.g. it does not check against common name if no subjectAltNames are given, it uses  IP in subjectAltNames like host names and the wildcard handling does not match against w*.example.org as required by rfc2818.

**Comment by genio** [comment]
@noxxi Is it still accurate to say we could pretty much delete `_check_sock` `_in_san` and `_cn_match` since we use IO::Socket::SSL and IO::Socket::SSL already takes care of these for us?

**Comment by noxxi** [comment]
> @noxxi Is it still accurate to say we could pretty much delete `_check_sock` `_in_san` and `_cn_match` since we use IO::Socket::SSL and IO::Socket::SSL already takes care of these for us?

Yes, IO::Socket::SSL fully verifies that the hostname matches the certificate and also checks SAN in the certificate for this.

**Comment by genio** [comment]
Closed via PR #71
