### ISSUE TITLE
cpan does not pick up release 6.06, stays with 6.04

### ISSUE THREAD

**Issue by noxxi** [libwww-perl/lwp-protocol-https#16]
The latest version of LWP::Protocol::https inside 02packages.details.txt.gz is 6.04 from GAAS, instead of 6.06 from MSCHILLI. Thus a default install of this module with cpan installs version 6.04 which is missing important fixes like support for https proxy. I don't know what need to be done to fix this, but the same maintainer change for libwww-perl worked, while for lwp-protocol-https not.

**Comment by oalders** [comment]
I think this issue can be closed now.
