### ISSUE TITLE
[PRC] How may I be of help

### ISSUE THREAD

**Issue by JJ** [libwww-perl/LWP-Protocol-https#50]
Hi,
I have been assigned this module for the May PRC. I have seen a few issues, one of them since 2012. Could I help with any of them? Would you want me to do something completely different?

**Comment by oalders** [comment]
@genio can you think of any issue in particular?

**Comment by oalders** [comment]
@JJ as a fairly simple PR you could set up one of the Travis builds to run coverage reports.  I've just switched this repo on at coveralls.io  Here's an example of how I set this up on another repo using the perl-helpers https://github.com/metacpan/metacpan-web/blob/master/.travis.yml

If you'd like to take this on, please reach out if you run into any problems or have questions.

**Comment by JJ** [comment]
OK, will do that.
