### ISSUE TITLE
https_proxy.t hangs on perl 5.27.8, Windows

### ISSUE THREAD

**Issue by chorny** [libwww-perl/LWP-Protocol-https#52]
Windows XP SP3 Russian
Strawberry perl 5.27.8 built with "gcc (i686-posix-dwarf, Built by strawberryperl.com project) 7.1.0"
Did not hang on 5.27.6, 5.27.1, 5.26.0.

All tests of https_proxy.t pass, it just does not exit.

**Comment by jkeenan** [comment]
Does this problem still exist?

In particular, does it exist on either perl-5.30.0 or in perl 5 blead?

Thank you very much.

**Comment by chorny** [comment]
Problem was fixed in perl 5.28.
