### ISSUE TITLE
Unable to install this in Ubuntu 20.04

### ISSUE THREAD

**Issue by JJ** [libwww-perl/LWP-Protocol-https#66]
It apparently requires a version of several libraries, `libssl` and `libcrypto`, which are not in the repositories or are in a different version, namely, 1.1.

When I create a symbolic link from the existing version to the required version, even so, it misses some Net::SSLeay file or some such; essentially, what #62 says. Is there a list of prerequisites needed for this to work somewhere? Together with instructions on how to install it?

The perl I'm using has been installed via perlbrew, so installing the Ubuntu package for this does not seem to install the needed system-level libraries. So I'm really stumped about what to do here.

**Comment by JJ** [comment]
OK, same solution as #65. Closing.

**Comment by oalders** [comment]
@JJ if you feel a documentation patch would have saved you some grief, I'd be happy to review a PR.

**Comment by JJ** [comment]
It certainly would. Will give it a try. Thanks
