### ISSUE TITLE
t/apache.t fails when apache.org changes content

### ISSUE THREAD

**Issue by ahollandECS** [libwww-perl/LWP-Protocol-https#67]
Currently, https://apache.org/ does not say "Apache Software Foundation" anywhere on it, so the test is failing. It should probably either be removed or pointed somewhere else.

**Comment by oalders** [comment]
Yikes! Yes, I think that line should be removed. Probably that file should also be moved from `.t/` to `.xt/`.

We would accept a PR for this.

Thoughts, @karenetheridge?

**Comment by oalders** [comment]
That test passes for me right now, so maybe it was a transient thing. Still would be helpful not to depend on content being on a 3rd party page.

**Comment by simbabque** [comment]
I agree. IIRC there is one in LWP itself as well that does this. Or have we removed that recently?

**Comment by oalders** [comment]
This should hopefully be fixed via #69. Thanks for reporting @ahollandECS!
